# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0004_remove_event_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pos',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
    ]
