# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0009_auto_20170321_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='likedBy',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
