# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0011_pref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='likedBy',
            new_name='likedby',
        ),
    ]
