# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0012_auto_20170322_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='likedby',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
