# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0014_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
        migrations.RemoveField(
            model_name='event',
            name='likedby',
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
